table FactTaxiDaily
	lineageTag: f7f09055-0924-4b61-b4f1-fe017defc373
	sourceLineageTag: [dbo].[FactTaxiDaily]

	measure 'Total Trips' = SUM(FactTaxiDaily[trip_count])
		formatString: 0
		lineageTag: 02598c3e-5652-44b8-9acf-5d62816e2f44

		changedProperty = Name

	measure 'Total Revenue USD' = SUM(FactTaxiDaily[total_fare_usd])
		lineageTag: e7104b69-b06b-4666-9ce1-e2e846ac67a6

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue EUR' = SUM(FactTaxiDaily[total_fare_eur])
		lineageTag: 9bd10d0c-52f1-4665-9056-93168534bd0f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Fare USD' = DIVIDE([Total Revenue USD], [Total Trips])
		lineageTag: 7e4624cc-c19f-4e2d-aafa-69cee8acc8d5

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue as % of US GDP' =
			
			DIVIDE(
			    [Total Revenue USD],
			    CALCULATE(
			        MAX(DimGDP[gdp_usd]),
			        DimGDP[country_code] = "US",
			        DimGDP[year] = SELECTEDVALUE(DimDate[year])
			    )
			) * 100
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: 720d5e53-f09c-474b-91e3-aeb54a694300

		changedProperty = Name

		changedProperty = FormatString

	measure 'Revenue USD YoY %' =
			
			VAR yr = SELECTEDVALUE(DimDate[year])
			VAR cur = [Total Revenue USD]
			VAR prev = CALCULATE(
			    [Total Revenue USD],
			    REMOVEFILTERS(DimDate),
			    DimDate[year] = yr - 1
			)
			RETURN IF(ISBLANK(yr), BLANK(), DIVIDE(cur - prev, prev))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6f8aa723-e7cf-4456-923d-260bcdcb382c

		changedProperty = Name

		changedProperty = FormatString

	measure 'Revenue USD YoY Label' =
			
			VAR pct = [Revenue USD YoY %]
			VAR yr = SELECTEDVALUE(DimDate[year])
			RETURN
			IF(
			    ISBLANK(pct) || ISBLANK(yr),
			    BLANK(),
			    IF(pct >= 0, "▲ +", "▼ ") & FORMAT(pct, "0.0%") & " vs " & (yr - 1)
			)
		lineageTag: ce748d26-6589-4f1b-bb4d-7a82852d035b

		changedProperty = Name

	measure 'Revenue EUR YoY %' =
			
			VAR yr = SELECTEDVALUE(DimDate[year])
			VAR cur = [Total Revenue EUR]
			VAR prev = CALCULATE(
			    [Total Revenue EUR],
			    REMOVEFILTERS(DimDate),
			    DimDate[year] = yr - 1
			)
			RETURN IF(ISBLANK(yr), BLANK(), DIVIDE(cur - prev, prev))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9fc943e7-8cf3-4e60-b9ee-3018e6c91d9c

		changedProperty = Name

		changedProperty = FormatString

	measure 'Revenue EUR YoY Label' =
			
			VAR pct = [Revenue EUR YoY %]
			VAR yr = SELECTEDVALUE(DimDate[year])
			RETURN
			IF(
			    ISBLANK(pct) || ISBLANK(yr),
			    BLANK(),
			    IF(pct >= 0, "▲ +", "▼ ") & FORMAT(pct, "0.0%") & " vs " & (yr - 1)
			)
		lineageTag: c90ec423-5e79-41f8-a57a-1a37c242450f

		changedProperty = Name

	measure 'Trips YoY %' =
			
			VAR yr = SELECTEDVALUE(DimDate[year])
			VAR cur = [Total Trips]
			VAR prev = CALCULATE(
			    [Total Trips],
			    REMOVEFILTERS(DimDate),
			    DimDate[year] = yr - 1
			)
			RETURN IF(ISBLANK(yr), BLANK(), DIVIDE(cur - prev, prev))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1cde6f6a-149a-4516-9c45-1d3f931116e8

		changedProperty = Name

		changedProperty = FormatString

	measure 'Trips YoY Label' =
			
			VAR pct = [Trips YoY %]
			VAR yr = SELECTEDVALUE(DimDate[year])
			RETURN
			IF(
			    ISBLANK(pct) || ISBLANK(yr),
			    BLANK(),
			    IF(pct >= 0, "▲ +", "▼ ") & FORMAT(pct, "0.0%") & " vs " & (yr - 1)
			)
		lineageTag: f5f814e8-d9e6-417c-9925-78e1db1ff0f2

		changedProperty = Name

	measure 'Avg Fare USD YoY %' =
			
			VAR yr = SELECTEDVALUE(DimDate[year])
			VAR cur = [Avg Fare USD]
			VAR prev = CALCULATE(
			    [Avg Fare USD],
			    REMOVEFILTERS(DimDate),
			    DimDate[year] = yr - 1
			)
			RETURN IF(ISBLANK(yr), BLANK(), DIVIDE(cur - prev, prev))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 659fdca4-f899-438b-aa4e-3bec817c4860

		changedProperty = Name

		changedProperty = FormatString

	measure 'Avg Fare USD YoY Label' =
			
			VAR pct = [Avg Fare USD YoY %]
			VAR yr = SELECTEDVALUE(DimDate[year])
			RETURN
			IF(
			    ISBLANK(pct) || ISBLANK(yr),
			    BLANK(),
			    IF(pct >= 0, "▲ +", "▼ ") & FORMAT(pct, "0.0%") & " vs " & (yr - 1)
			)
		lineageTag: 5b725f9d-07d7-4b63-b65d-68d2045873f8

		changedProperty = Name

	measure 'Correlation Trips vs PM2.5' =
			
			VAR S =
			    SUMMARIZE(
			        DimDate,
			        DimDate[date_key],
			        "X", [Total Trips],
			        "Y", [Avg PM2.5]
			    )
			VAR F = FILTER(S, NOT ISBLANK([X]) && NOT ISBLANK([Y]))
			VAR n = COUNTROWS(F)
			VAR sX = SUMX(F, [X])
			VAR sY = SUMX(F, [Y])
			VAR sXY = SUMX(F, [X] * [Y])
			VAR sX2 = SUMX(F, [X] * [X])
			VAR sY2 = SUMX(F, [Y] * [Y])
			RETURN DIVIDE(
			    n * sXY - sX * sY,
			    SQRT((n * sX2 - sX * sX) * (n * sY2 - sY * sY))
			)
		formatString: 0.000
		lineageTag: b2f6a8a3-51e3-4b86-b877-4477cc0c3879

		changedProperty = Name

		changedProperty = FormatString

	measure 'Correlation Trips vs NO2' =
			
			VAR S =
			    SUMMARIZE(
			        DimDate,
			        DimDate[date_key],
			        "X", [Total Trips],
			        "Y", [Avg NO2]
			    )
			VAR F = FILTER(S, NOT ISBLANK([X]) && NOT ISBLANK([Y]))
			VAR n = COUNTROWS(F)
			VAR sX = SUMX(F, [X])
			VAR sY = SUMX(F, [Y])
			VAR sXY = SUMX(F, [X] * [Y])
			VAR sX2 = SUMX(F, [X] * [X])
			VAR sY2 = SUMX(F, [Y] * [Y])
			RETURN DIVIDE(
			    n * sXY - sX * sY,
			    SQRT((n * sX2 - sX * sX) * (n * sY2 - sY * sY))
			)
		formatString: 0.000
		lineageTag: 087f9302-6ebc-4cad-ba94-0847645f1ba9

		changedProperty = Name

		changedProperty = FormatString

	measure 'Correlation Trips vs O3' =
			
			VAR S =
			    SUMMARIZE(
			        DimDate,
			        DimDate[date_key],
			        "X", [Total Trips],
			        "Y", [Avg O3]
			    )
			VAR F = FILTER(S, NOT ISBLANK([X]) && NOT ISBLANK([Y]))
			VAR n = COUNTROWS(F)
			VAR sX = SUMX(F, [X])
			VAR sY = SUMX(F, [Y])
			VAR sXY = SUMX(F, [X] * [Y])
			VAR sX2 = SUMX(F, [X] * [X])
			VAR sY2 = SUMX(F, [Y] * [Y])
			RETURN DIVIDE(
			    n * sXY - sX * sY,
			    SQRT((n * sX2 - sX * sX) * (n * sY2 - sY * sY))
			)
		formatString: 0.000
		lineageTag: 9b9f9e16-9c50-4e51-80e4-89be98bef8ff

		changedProperty = Name

		changedProperty = FormatString

	measure 'Avg Fare EUR' = DIVIDE([Total Revenue EUR], [Total Trips])
		lineageTag: b9310b3c-8ef2-4753-8998-36bc84d0c714

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: c6665368-af06-49b5-946c-a95735fc0027
		sourceLineageTag: date_key
		summarizeBy: none
		sourceColumn: date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column zone_key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: a821a782-c50d-441b-a458-e21364c0f7ab
		sourceLineageTag: zone_key
		summarizeBy: none
		sourceColumn: zone_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fx_key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 00d39a5e-82de-49f4-a8d8-8335ad0c6fcb
		sourceLineageTag: fx_key
		summarizeBy: none
		sourceColumn: fx_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column trip_count
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a3555d0c-6aab-49a2-b5c5-46635c744909
		sourceLineageTag: trip_count
		summarizeBy: sum
		sourceColumn: trip_count

		annotation SummarizationSetBy = Automatic

	column total_fare_usd
		dataType: double
		sourceProviderType: float
		lineageTag: 9ced6a7e-c7f4-4d62-84af-942675a64fcc
		sourceLineageTag: total_fare_usd
		summarizeBy: sum
		sourceColumn: total_fare_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_fare_eur
		dataType: double
		sourceProviderType: float
		lineageTag: 988e94d5-d038-4916-90a7-5b51b482e6ba
		sourceLineageTag: total_fare_eur
		summarizeBy: sum
		sourceColumn: total_fare_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_fare_usd
		dataType: double
		sourceProviderType: float
		lineageTag: a9b45c36-cfb9-43ba-8f76-ee6eb89ad55c
		sourceLineageTag: avg_fare_usd
		summarizeBy: none
		sourceColumn: avg_fare_usd

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_trip_duration_min
		dataType: double
		sourceProviderType: float
		lineageTag: 8cdaf258-cd82-4b17-bf14-72cf7b3db985
		sourceLineageTag: avg_trip_duration_min
		summarizeBy: none
		sourceColumn: avg_trip_duration_min

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_trip_distance_mi
		dataType: double
		sourceProviderType: float
		lineageTag: 5c264753-5729-4a84-a342-ccea4bdb575d
		sourceLineageTag: avg_trip_distance_mi
		summarizeBy: none
		sourceColumn: avg_trip_distance_mi

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_passengers
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d5f84648-2ce5-4375-a569-57e70e07ed8c
		sourceLineageTag: total_passengers
		summarizeBy: sum
		sourceColumn: total_passengers

		annotation SummarizationSetBy = Automatic

	partition FactTaxiDaily = entity
		mode: directLake
		source
			entityName: FactTaxiDaily
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

